source "https://rubygems.org"
#ruby "3.0.3"

#gem "puma"
#gem "sinatra"
#gem "sinatra-flash"
#gem "sinatra-partial"
#gem "bcrypt"

group :test do 
  gem "rspec"
  gem "capybara"
  #gem "rspec-sinatra"
  gem "cucumber"
  gem "coveralls", require: false
end
