FROM axel9691/debian:11.6-en

LABEL maintainer 'axelkrebs@online.de'

RUN apt-get -y update 
RUN apt install -y autoconf automake bison cmake dpkg-dev gcc git libssl-dev libtool libz-dev pkg-config python3 make wget

CMD ["/bin/bash", "-c", "tail -f /dev/null"]