FROM axel9691/almalinux:9.3-en

RUN apt-get update -y 

# Install GraalVM-Ruby runtime as root
#RUN wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.1/graalvm-ce-java19-linux-amd64-22.3.1.tar.gz

#Not yet supported!!!

# set password etc

CMD ["/bin/bash", "-c", "tail -f /dev/null"]